name: Trigger auto deployment for service-integration-18221094

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/service-integration-18221094-AutoDeployTrigger-ba9758c2-55d9-414c-91c8-aeb18161c9e6.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICEINTEGRATION18221094_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: integration18221094.azurecr.io
          registryUsername: ${{ secrets.SERVICEINTEGRATION18221094_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERVICEINTEGRATION18221094_REGISTRY_PASSWORD }}
          containerAppName: service-integration-18221094
          resourceGroup: TST
          imageToBuild: integration18221094.azurecr.io/service-integration-18221094:${{ github.sha }}
          

     

